#!/usr/bin/env python3
"""Regenerate catalog/known-skills.txt from the agents' live skill corpora.

`validate.py` checks that every `metadata.related-skills` entry resolves either in
this repo or in this registry — so a bridge skill may cross-link to a skill the
user already has installed (system-design-theory, web-pentest, supabase, ...)
without the validator failing, while still catching typos.

Run after installing or removing skill sets.

Usage
  python3 scripts/gen-known-skills.py
  python3 scripts/gen-known-skills.py --check   # exit 1 if the file is stale
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "catalog" / "known-skills.txt"
HOME = Path.home()

ROOTS = [
    HOME / ".hermes/skills",
    HOME / ".config/opencode/skills",
    HOME / ".vibe/skills",
    HOME / ".agents/skills",
]
PLUGIN_ROOTS = [
    HOME / ".gemini/antigravity-cli/plugins",
    HOME / ".gemini/config/plugins",
]

HEADER = """# Skills already installed across Hermes / OpenCode / Antigravity / Vibe.
# Generated by scripts/gen-known-skills.py — do not hand-edit.
# Bridge and BD skills may cross-reference these names in metadata.related-skills.
# Regenerate after installing or removing a skill set.
"""


def collect() -> set[str]:
    names: set[str] = set()
    for root in ROOTS:
        if not root.is_dir():
            continue
        for p in root.iterdir():
            if (p.is_dir() or p.is_symlink()) and not p.name.startswith("."):
                if (p / "SKILL.md").is_file() or p.is_symlink():
                    names.add(p.name)
    # Hermes nests skills under category directories.
    hermes = HOME / ".hermes/skills"
    if hermes.is_dir():
        for p in hermes.rglob("SKILL.md"):
            try:
                rel = p.relative_to(hermes)
            except ValueError:
                continue
            # Skip hidden *relative* dirs (e.g. .archive, .curator_backups); the
            # absolute path always contains ".hermes", so test the relative one.
            if any(part.startswith(".") for part in rel.parts):
                continue
            names.add(p.parent.name)
    for root in PLUGIN_ROOTS:
        if not root.is_dir():
            continue
        for plugin in root.iterdir():
            skills = plugin / "skills"
            if skills.is_dir():
                for p in skills.iterdir():
                    if p.is_dir():
                        names.add(p.name)
    return names


def main() -> int:
    repo_skills = {d.name for d in (REPO / "skills").iterdir() if d.is_dir()}
    known = sorted(collect() - repo_skills)
    rendered = HEADER + "\n".join(known) + "\n"

    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != rendered:
            print(f"stale: {OUT} differs from the live corpora — re-run without --check")
            return 1
        print(f"up to date ({len(known)} external skill names)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} — {len(known)} external skill names "
          f"(+{len(repo_skills)} from this repo)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
