#!/usr/bin/env python3
"""Maintain the cross-link registries used to validate skill references.

Two files, deliberately separated by what they disclose:

  catalog/known-skills.public.txt   COMMITTED. A curated allowlist of public
                                    skill names this repo cross-references. It
                                    ships with the repository.

  catalog/known-skills.local.txt    GITIGNORED. A generated snapshot of every
                                    skill installed on this machine. It never
                                    leaves the machine: the full corpus reveals
                                    which private projects and tooling an author
                                    runs.

`validate.py` merges both, so the public repo validates against public names and
a developer machine validates against everything it actually has.

Usage
  python3 scripts/gen-known-skills.py            # refresh the local snapshot
  python3 scripts/gen-known-skills.py --public    # refresh the public allowlist
  python3 scripts/gen-known-skills.py --check     # exit 1 if either is stale
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "catalog"
LOCAL = CATALOG / "known-skills.local.txt"
PUBLIC = CATALOG / "known-skills.public.txt"
HOME = Path.home()

ROOTS = [
    HOME / ".hermes/skills",
    HOME / ".config/opencode/skills",
    HOME / ".vibe/skills",
    HOME / ".agents/skills",
]
PLUGIN_ROOTS = [
    HOME / ".gemini/antigravity-cli/plugins",
    HOME / ".gemini/config/plugins",
]

# Skill-name families that are private to the authoring machine and must never
# be published. Read from a gitignored file rather than hardcoded here: listing
# the project names in a public script would disclose them just as surely as the
# corpus snapshot did.
PRIVATE_FILE = CATALOG / ".private-prefixes"


def private_prefixes() -> tuple[str, ...]:
    """Private name prefixes. Absent file means no filtering, which is safe:
    the public allowlist is limited to names this repo actually references."""
    if not PRIVATE_FILE.is_file():
        return ()
    return tuple(
        line.strip()
        for line in PRIVATE_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    )

LOCAL_HEADER = """# Skills installed on THIS machine, across Hermes / OpenCode / Antigravity / Vibe.
# LOCAL ONLY - gitignored, never published. This is a snapshot of one author's
# corpus and reveals private projects and tooling.
# Generated by scripts/gen-known-skills.py. Regenerate after installing skills.
"""

PUBLIC_HEADER = """# Public corpus allowlist (committed).
#
# Skill names that this repository's skills and docs cross-reference and that are
# expected to be present in a normal agent installation. Deliberately limited to
# names from public sources: the full corpus of the machine that authored this
# suite is NOT published. Anything machine-specific lives in
# known-skills.local.txt, which is generated locally and gitignored.
#
# Regenerate with: python3 scripts/gen-known-skills.py --public
"""


def collect() -> set[str]:
    names: set[str] = set()
    for root in ROOTS:
        if not root.is_dir():
            continue
        for p in root.iterdir():
            if (p.is_dir() or p.is_symlink()) and not p.name.startswith("."):
                if (p / "SKILL.md").is_file() or p.is_symlink():
                    names.add(p.name)
    # Hermes nests skills under category directories.
    hermes = HOME / ".hermes/skills"
    if hermes.is_dir():
        for p in hermes.rglob("SKILL.md"):
            try:
                rel = p.relative_to(hermes)
            except ValueError:
                continue
            # Skip hidden *relative* dirs (e.g. .archive, .curator_backups); the
            # absolute path always contains ".hermes", so test the relative one.
            if any(part.startswith(".") for part in rel.parts):
                continue
            names.add(p.parent.name)
    for root in PLUGIN_ROOTS:
        if not root.is_dir():
            continue
        for plugin in root.iterdir():
            skills = plugin / "skills"
            if skills.is_dir():
                for p in skills.iterdir():
                    if p.is_dir():
                        names.add(p.name)
    return names


def repo_skills() -> set[str]:
    return {d.name for d in (REPO / "skills").iterdir() if d.is_dir()}


def build_local() -> str:
    known = sorted(collect() - repo_skills())
    return LOCAL_HEADER + "\n".join(known) + "\n"


def build_public() -> str:
    """Names this repo cites that exist in the local corpus, minus private families."""
    corpus = collect()
    referenced: set[str] = set()
    files = list((REPO / "skills").rglob("*.md")) + [
        CATALOG / "CATALOG.md",
        REPO / "README.md",
        REPO / "AGENTS.md",
        REPO / "docs" / "architecture.md",
        REPO / "docs" / "linking-model.md",
    ]
    for f in files:
        if f.is_file():
            referenced |= set(re.findall(r"`([a-z][a-z0-9-]{2,})`", f.read_text(encoding="utf-8")))
    referenced = {c for c in referenced if not c.endswith((".md", ".py", ".mjs", ".json", ".txt", ".yml"))}
    keep = sorted(
        c for c in referenced
        if c in corpus and not c.startswith(private_prefixes()) and c not in repo_skills()
    )
    return PUBLIC_HEADER + "\n".join(keep) + "\n"


def main() -> int:
    if "--check" in sys.argv:
        stale = []
        for path, rendered in ((LOCAL, build_local()), (PUBLIC, build_public())):
            # A missing local file is the normal state on a fresh clone or CI.
            if path is LOCAL and not path.is_file():
                continue
            if (path.read_text(encoding="utf-8") if path.is_file() else "") != rendered:
                stale.append(path.name)
        if stale:
            print(f"stale: {', '.join(stale)} differ from the live corpora")
            return 1
        print("registries up to date")
        return 0

    if "--public" in sys.argv:
        PUBLIC.write_text(build_public(), encoding="utf-8")
        print(f"wrote {PUBLIC.name} ({len(build_public().splitlines())} lines incl. header)")
        return 0

    LOCAL.parent.mkdir(parents=True, exist_ok=True)
    rendered = build_local()
    LOCAL.write_text(rendered, encoding="utf-8")
    n = len([l for l in rendered.splitlines() if l and not l.startswith("#")])
    print(f"wrote {LOCAL.name} — {n} installed skill names (local only, gitignored)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
