#!/usr/bin/env node
/**
 * Generate CREDITS.md and registry/installed.json from registry/sources.json.
 *
 * Attribution is generated, never hand-maintained: a hand-written credits file
 * drifts the moment a source is added or a licence changes. Run `npm run credits`
 * after editing registry/sources.json, and the CI `--check` mode fails the build
 * if the committed files no longer match the registry.
 *
 * Usage
 *   node scripts/gen-credits.mjs
 *   node scripts/gen-credits.mjs --check   # exit 1 if stale
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCES = join(REPO, "registry/sources.json");
const OUT_CREDITS = join(REPO, "CREDITS.md");
const OUT_JSON = join(REPO, "registry/installed.json");

const HEADER = `# Credits

venture-skills is two things: skills we author, and skills we curate from other
people's repositories.

**We do not vendor other people's work.** Third-party skills are fetched at
install time by \`scripts/install-external.py\` from the upstream repository,
pinned to the revision you choose, and installed alongside our own. Nothing in
\`skills/\` comes from anywhere but this repository.

The \`skills/\` directory is MIT licensed (see LICENSE). Everything listed below
stays under its own upstream licence, and remains the property of its authors.
If you are a source author and want a change to how you are credited, open an
issue.

Generated by \`scripts/gen-credits.mjs\` from \`registry/sources.json\`. Do not
edit by hand.
`;

function build() {
  if (!existsSync(SOURCES)) throw new Error(`missing ${SOURCES}`);
  const sources = JSON.parse(readFileSync(SOURCES, "utf8")).sources ?? [];
  const enabled = sources.filter((s) => s.enabled !== false);
  const disabled = sources.filter((s) => s.enabled === false);

  const lines = [HEADER, `## Curated sources (${enabled.length})\n`];
  for (const s of enabled) {
    const include = s.include ?? [];
    lines.push(`### [${s.repo}](https://github.com/${s.repo})`);
    lines.push("");
    lines.push(`- **Licence:** ${s.license ?? "see upstream repository"}`);
    lines.push(`- **Pinned revision:** \`${s.ref ?? "main"}\``);
    lines.push(`- **Skills curated:** ${include.length}`);
    lines.push("");
    lines.push(`${s.why}`);
    lines.push("");
    const excluded = s.exclude ?? [];
    if (excluded.length) {
      lines.push(
        `Deliberately **not** imported (${excluded.length}): ${excluded.map((e) => `\`${e}\``).join(", ")}. ` +
          `These overlap skills this repository authors, and importing both would create routing ambiguity for agents.`
      );
      lines.push("");
    }
    lines.push("<details>");
    lines.push(`<summary>Curated skill names (${include.length})</summary>`);
    lines.push("");
    for (const n of include) lines.push(`- \`${n}\``);
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  if (disabled.length) {
    lines.push(`## Available but disabled (${disabled.length})\n`);
    for (const s of disabled) {
      lines.push(
        `- [${s.repo}](https://github.com/${s.repo}) — ${s.license ?? "see upstream"}. ${s.why ?? ""}`
      );
    }
    lines.push("");
  }

  const json = {
    generated_by: "scripts/gen-credits.mjs",
    note: "Machine-readable attribution. Skills are fetched from these repositories at install time, not vendored.",
    sources: enabled.map((s) => ({
      repo: s.repo,
      url: `https://github.com/${s.repo}`,
      license: s.license ?? null,
      ref: s.ref ?? "main",
      why: s.why ?? null,
      skill_count: (s.include ?? []).length,
      skills: s.include ?? [],
      excluded: s.exclude ?? [],
    })),
  };

  return { credits: lines.join("\n").replace(/\n{3,}/g, "\n\n") + "\n", json };
}

function main() {
  const { credits, json } = build();
  const rendered = JSON.stringify(json, null, 2) + "\n";
  if (process.argv.includes("--check")) {
    const a = existsSync(OUT_CREDITS) ? readFileSync(OUT_CREDITS, "utf8") : "";
    const b = existsSync(OUT_JSON) ? readFileSync(OUT_JSON, "utf8") : "";
    if (a !== credits || b !== rendered) {
      console.error("stale: CREDITS.md or registry/installed.json differ from registry/sources.json");
      console.error("run: npm run credits");
      return 1;
    }
    console.log(`up to date (${json.sources.length} sources, ${json.sources.reduce((n, s) => n + s.skill_count, 0)} skills)`);
    return 0;
  }
  writeFileSync(OUT_CREDITS, credits);
  writeFileSync(OUT_JSON, rendered);
  console.log(`wrote CREDITS.md and registry/installed.json (${json.sources.length} sources)`);
  return 0;
}

process.exit(main());
